# Generated by Django 6.0.2 on 2026-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_currency', models.CharField(max_length=10)),
                ('buy_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('result', models.FloatField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],  
        ),
    ]
